// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: Auto gauge

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_gauge_bg = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_gauge_bg, &ui_img_1920837027);
lv_obj_set_width( ui_Image_gauge_bg, LV_SIZE_CONTENT);  /// 466
lv_obj_set_height( ui_Image_gauge_bg, LV_SIZE_CONTENT);   /// 466
lv_obj_set_align( ui_Image_gauge_bg, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_gauge_bg, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_gauge_bg, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label1 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 5 );
lv_obj_set_y( ui_Label1, -120 );
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"x1000r/min");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xC2030F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_t20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, 46 );
lv_obj_set_y( ui_Label2, 130 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"rpm");
lv_obj_set_style_text_color(ui_Label2, lv_color_hex(0xC2030F), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label2, &ui_font_t20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label_rpm = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_Label_rpm, 164);
lv_obj_set_height( ui_Label_rpm, 58);
lv_obj_set_x( ui_Label_rpm, 105 );
lv_obj_set_y( ui_Label_rpm, 99 );
lv_obj_set_align( ui_Label_rpm, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label_rpm,"10000");
lv_obj_set_style_text_color(ui_Label_rpm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label_rpm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Label_rpm, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label_rpm, &ui_font_t50, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image_car = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_car, &ui_img_images_car_icon_png);
lv_obj_set_width( ui_Image_car, LV_SIZE_CONTENT);  /// 151
lv_obj_set_height( ui_Image_car, LV_SIZE_CONTENT);   /// 26
lv_obj_set_x( ui_Image_car, 107 );
lv_obj_set_y( ui_Image_car, 61 );
lv_obj_set_align( ui_Image_car, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image_car, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_car, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_blend_mode(ui_Image_car, LV_BLEND_MODE_NORMAL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_Image_car, 200, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Arc_rpm = lv_arc_create(ui_Screen1);
lv_obj_set_width( ui_Arc_rpm, 409);
lv_obj_set_height( ui_Arc_rpm, 409);
lv_obj_set_align( ui_Arc_rpm, LV_ALIGN_CENTER );
lv_arc_set_value(ui_Arc_rpm, 0);
lv_arc_set_bg_angles(ui_Arc_rpm,90,0);
lv_obj_set_style_arc_color(ui_Arc_rpm, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc_rpm, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc_rpm, false, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_arc_color(ui_Arc_rpm, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_arc_opa(ui_Arc_rpm, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_width(ui_Arc_rpm, 100, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_rounded(ui_Arc_rpm, false, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_arc_img_src( ui_Arc_rpm, &ui_img_1251939133, LV_PART_INDICATOR | LV_STATE_DEFAULT );

lv_obj_set_style_bg_color(ui_Arc_rpm, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Arc_rpm, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_Image_gauge_needle = lv_img_create(ui_Screen1);
lv_img_set_src(ui_Image_gauge_needle, &ui_img_874541913);
lv_obj_set_width( ui_Image_gauge_needle, 43);
lv_obj_set_height( ui_Image_gauge_needle, 171);
lv_obj_set_x( ui_Image_gauge_needle, 211 );
lv_obj_set_y( ui_Image_gauge_needle, 293 );
lv_obj_add_flag( ui_Image_gauge_needle, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image_gauge_needle, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_pivot(ui_Image_gauge_needle,21,-60);

}
